### PR TITLE
Start testing on travis

### PR DESCRIPTION
**Pull request by springmeyer**
Working on getting travis testing enabled. Mostly a port from tippecanoe. Ideally in the future could pull in advanced tooling from https://github.com/mapbox/hpp-skel/blob/master/.travis.yml as a followup.

### CODE REVIEW

**Comment by springmeyer** [comment]
This is working now well enough for the tests to run. Now hitting some errors on builds with the `-fsanitize=integer,undefined`:

```
tile.cpp:1359:23: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'unsigned long'
./tile-count-tile -f -1 -y count -s16 -o tests/tmp/2.mbtiles tests/tmp/2.count
```

**Comment by ericfischer** [comment]
Thanks. This reveals that I am setting the maxzoom in the tilestats too early, before it is necessarily known.

**Comment by springmeyer** [comment]
@ericfischer - that makes sense. I'm going to pause on this branch now for the evening. I'm hoping my last commit will get the normal jobs green (that don't use `-fsanitize`). Maybe when you have a minute you could pick up and commit to this branch any fixes needed to get the `-fsanitize` jobs green?

**Comment by ericfischer** [comment]
Sure, I will merge your changes after I fix the problem. Thank you for getting this into Travis!

**Comment by springmeyer** [comment]
> Sure, I will merge your changes after I fix the problem.

Sounds good. Ended up continuing to poke at fixing up this branch while I worked on other things. It should now be passing for all jobs except the one that is hitting `unsigned integer overflow` due to the `-fsanitize` catching it. So, it should work to merge this after fixing that in master, or feel free to commit here - whatever you prefer.

**Pull request merged**
